server:
  port: 2222

spring:
  application:
    name: member-service
  # 热部署
  devtools:
    restart:
      enable: true
  # Redis配置
  redis:
    # Redis服务器地址
    host: 127.0.0.1
    # Redis服务器连接端口
    port: 6379
    jedis:
      pool:
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: 10000
        # 连接池中的最大空闲连接
        max-idle: 10
        # 连接池中的最小空闲连接
        min-idle: 0
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 100
    # 连接超时时间（毫秒）
    timeout: 5000
  # 分布式数据源Atomikos配置
  jta:
    atomikos:
      properties:
        # 配置日志保存路径
        log-base-dir: ./log/member-service
      connectionfactory:
        local-transaction-mode: true
        max-pool-size: 30
  # activemq连接信息
  activemq:
    user: admin
    password: admin
    broker-url: tcp://localhost:61617
    pool:
      enabled: true
      max-connections: 5
      reconnect-on-exception: true
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: admin
    password: admin

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/
  instance:
    preferIpAdress:
      instance-id: ${spring.cloud.client.ipAddress}:${server.port}

mysql:
  datasource:
    # DB1
    db1:
      url: jdbc:mysql://localhost:53306/XUZ_DEMO?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: root
      password: 123456
      minPoolSize: 3
      maxPoolSize: 25
      maxLifetime: 20000
      borrowConnectionTimeout: 30
      loginTimeout: 30
      maintenanceInterval: 60
      maxIdleTime: 60
      testQuery: select 1

# 队列
email:
  messages:
    queue: messages_queue_01
    topic: Topic_01


# mybatis配置
#mybatis:
#  type-aliases-package: com.xuz.myproject.spcbasedata.mapper.db1.*
#  mapper-locations: classpath:db1-mapper/*.xml
#  # 表字段映射
#  configuration:
#    map-underscore-to-camel-case: true
