server:
  port: 3332

spring:
  application:
    name: feign-consumer-member-web
  devtools:
    restart:
      enabled: true

ribbon:
  ReadTimeout: 6000
  ConnectionTimeout: 6000

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/

